spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none  # 与 prod 一致，全部用 Flyway 管理；如需临时自动建表可手动改回 update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/migration-dev # 可选的开发专用迁移目录（目前可空）
    baseline-on-migrate: true
  sql:
    init:
      mode: never # 彻底避免 schema.sql

# logging:
#   level:
#     root: INFO
#     org:
#       hibernate:
#         SQL: DEBUG

logging:
  level:
    com:
      altair288:
        class_management:
          config:
            LoggingAccessDeniedHandler: DEBUG
            SseAccessDeniedHandler: DEBUG
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG

# 提示：新增表/列时请：
# 1) 在 db/migration 下新增 V{N}__desc.sql（结构变更）
# 2) 如仅 dev 演示数据放 db/migration-dev 里用 R__ 前缀（可重复执行），不要进 prod

