spring:
  config:
    activate:
      on-profile: prod
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration # 彻底禁用默认 schema.sql 初始化
  jpa:
    hibernate:
      ddl-auto: none # 生产不让 Hibernate 改结构
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true # 若已有手工建库可基线
    table: flyway_schema_history
    validate-on-migrate: true
  sql:
    init:
      mode: never  # 禁止执行 classpath 下的 schema.sql，全部交给 Flyway
  mail:
    host: ${SMTP_HOST:smtp.example.com}
    port: ${SMTP_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# 可按需添加连接池/监控等 prod 专用配置

security:
  password-reset:
    token-expire-minutes: 30
    ip-hourly-limit: 20
    frontend-base-url: https://altair288.eu.org
    mail-from: ${PASSWORD_RESET_MAIL_FROM:no-reply@altair288.eu.org}

mail:
  provider: ${MAIL_PROVIDER:resend} # 可选: smtp | worker | resend
  resend:
    api-key: ${RESEND_API_KEY:}
  worker:
    base-url: ${MAIL_WORKER_BASE_URL:}
    hmac-secret: ${MAIL_WORKER_HMAC_SECRET:}
